<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="SHIVA" name="com.hyr.groupTest.TesrGroupDependency" tests="6" failures="0" timestamp="24 Jan 2023 06:52:12 GMT" time="0.000" errors="1">
  <testcase name="test1" time="0.000" classname="com.hyr.groupTest.TesrGroupDependency"/>
  <testcase name="test3" time="0.000" classname="com.hyr.groupTest.TesrGroupDependency">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test5" time="0.000" classname="com.hyr.groupTest.TesrGroupDependency">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test6" time="0.000" classname="com.hyr.groupTest.TesrGroupDependency">
    <skipped/>
  </testcase> <!-- test6 -->
  <testcase name="test2" time="0.000" classname="com.hyr.groupTest.TesrGroupDependency">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.hyr.groupTest.TesrGroupDependency.test2(TesrGroupDependency.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test2 -->
  <testcase name="test4" time="0.000" classname="com.hyr.groupTest.TesrGroupDependency"/>
</testsuite> <!-- com.hyr.groupTest.TesrGroupDependency -->
